<?php

use Illuminate\Database\Seeder;
use App\Alimento;

class AlimentosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            [
                'nombre' => 'Atun',
                'imagen' => 'atun.png',
                'calorias' => '289',
                'carbohidratos' => '0',
                'proteinas' => '23',
                'grasas' => '22',
                'informacion' => 'Contiene gran contenido en ácidos grasos omega-3 ya que ayudan a proteger el corazón, reforzar la circulación y prevenir enfermedades cardíacas',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Carne cerdo',
                'imagen' => 'carne_cerdo.png',
                'calorias' => '147',
                'carbohidratos' => '0',
                'proteinas' => '21',
                'grasas' => '7',
                'informacion' => 'Ayuda a mantener la masa muscular y el correcto mantenimiento de los huesos.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Carne pollo',
                'imagen' => 'carne_pollo.png',
                'calorias' => '121',
                'carbohidratos' => '0',
                'proteinas' => '20',
                'grasas' => '4',
                'informacion' => 'Es rico en fósforo, un mineral esencial que nutre a los dientes y huesos, así como a los riñones y el hígado.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Carne res',
                'imagen' => 'carne_res.png',
                'calorias' => '208',
                'carbohidratos' => '0',
                'proteinas' => '26',
                'grasas' => '11',
                'informacion' => 'tiene un alto contenido de sarcosina, un aminoácido natural que le suministra energía al cuerpo y además ayuda al mantenimiento de los músculo',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Carne soya',
                'imagen' => 'carne_soya.png',
                'calorias' => '153',
                'carbohidratos' => '12',
                'proteinas' => '18',
                'grasas' => '4',
                'informacion' => 'No produce pesadez en el estómago, Ayuda a prevenir el estreñimiento por su alto contenido de fibra y Reduce el colesterol.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Huevo',
                'imagen' => 'huevo.png',
                'calorias' => '147',
                'carbohidratos' => '1',
                'proteinas' => '12',
                'grasas' => '11',
                'informacion' => 'Contiene proteínas que aportan los aminoácidos que nuestro organismo requiere.',
                'cantidad' => '55',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Pescado',
                'imagen' => 'pescado.png',
                'calorias' => '132',
                'carbohidratos' => '0',
                'proteinas' => '20',
                'grasas' => '6',
                'informacion' => 'El pescado contiene de forma natural ácidos grasos Omega – 3, beneficiosos para la salud.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '1',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Arroz',
                'imagen' => 'arroz.png',
                'calorias' => '130',
                'carbohidratos' => '28',
                'proteinas' => '3',
                'grasas' => '1',
                'informacion' => 'Los pescados son una fuente de proteinas de calidad, ya que contienen los aminoácidos esciales en las proporciones adecuadas.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Avena',
                'imagen' => 'avena.png',
                'calorias' => '34',
                'carbohidratos' => '9',
                'proteinas' => '2',
                'grasas' => '1',
                'informacion' => 'baja el colesterol, controla el azucar, protege el cancer, fortalece la musculatura, equilibra el sistema digestivo.',
                'cantidad' => '14',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '9'
            ],
            [
                'nombre' => 'Berenjena',
                'imagen' => 'berenjena.png',
                'calorias' => '14',
                'carbohidratos' => '3',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'ideal para  combatir el cáncer, el envejecimiento celular, las infecciones, virus y  bacterias nocivas',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '1'
            ],
            [
                'nombre' => 'Camote',
                'imagen' => 'camote.png',
                'calorias' => '76',
                'carbohidratos' => '20',
                'proteinas' => '2',
                'grasas' => '1',
                'informacion' => 'Previene las arrugas, ayuda al crecimiento del cabello y las uñas.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '6'
            ],
            [
                'nombre' => 'Choclo',
                'imagen' => 'choclo.png',
                'calorias' => '104',
                'carbohidratos' => '19',
                'proteinas' => '3',
                'grasas' => '1',
                'informacion' => 'Evita la retención de líquidos y mejora el tránsito digestivo.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Frejol',
                'imagen' => 'frejol.png',
                'calorias' => '138',
                'carbohidratos' => '25',
                'proteinas' => '9',
                'grasas' => '1',
                'informacion' => 'Aportan energía gracias a su elevado contenido en carbohidratos de lenta absorción.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Garbanzos',
                'imagen' => 'garbanzo.png',
                'calorias' => '164',
                'carbohidratos' => '27',
                'proteinas' => '9',
                'grasas' => '3',
                'informacion' => 'Disminuyen el colesterol malo y protegen contra enfermedades cardiovasculares.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Lentejas',
                'imagen' => 'lenteja.png',
                'calorias' => '116',
                'carbohidratos' => '20',
                'proteinas' => '9',
                'grasas' => '1',
                'informacion' => 'Las lentejas son ricas en fibra, lo que ayuda a regular el tránsito intestinal y combate el estreñimiento y reduce los niveles de azúcar en sangre.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Pan blanco',
                'imagen' => 'pan.png',
                'calorias' => '233',
                'carbohidratos' => '50',
                'proteinas' => '8',
                'grasas' => '2',
                'informacion' => 'Contiene calcio, beneficioso para el sistema óseo y Tiene un alto contenido en carbohidratos, por lo que nos ofrece mucha energía para sentirnos activos en nuestro día a día.',
                'cantidad' => '40',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '9'
            ],
            [
                'nombre' => 'Papa',
                'imagen' => 'papa.png',
                'calorias' => '86',
                'carbohidratos' => '19',
                'proteinas' => '2',
                'grasas' => '0.1',
                'informacion' => 'Contienen gran cantidad de potasio, por lo que ayudan a bajar la presión arterial del organismo.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '6'
            ],
            [
                'nombre' => 'Pasta',
                'imagen' => 'pasta.png',
                'calorias' => '158',
                'carbohidratos' => '31',
                'proteinas' => '6',
                'grasas' => '1',
                'informacion' => 'Mantiene el nivel de glucemia (cantidad de azúcar en la sangre) y favorece el correcto funcionamiento del sistema gastrointestinal.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Quinua',
                'imagen' => 'quinua.png',
                'calorias' => '120',
                'carbohidratos' => '21',
                'proteinas' => '4',
                'grasas' => '2',
                'informacion' => 'Es rica en aminoácidos, que influyen en el desarrollo cerebral. Su contenido en grasa es rico en Omega 6.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Yuca',
                'imagen' => 'yuca.png',
                'calorias' => '159',
                'carbohidratos' => '38',
                'proteinas' => '1.4',
                'grasas' => '0.3',
                'informacion' => 'Destaca la vitamina K, que nos protege los huesos y nos previene el desarrollo de la osteoporosis.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '2',
                'categoria_id' => '6'
            ],
            [
                'nombre' => 'Almendras',
                'imagen' => 'almendras.png',
                'calorias' => '565',
                'carbohidratos' => '4',
                'proteinas' => '17',
                'grasas' => '54',
                'informacion' => 'Con el consumo regular de las almendras podemos aumentar la función cerebral, de manera que este órgano se mantenga lúcido y activo.',
                'cantidad' => '14',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '4'
            ],
            [
                'nombre' => 'Chia',
                'imagen' => 'chia.png',
                'calorias' => '486',
                'carbohidratos' => '42',
                'proteinas' => '17',
                'grasas' => '31',
                'informacion' => 'Son muy ricas en ácidos grasos omega-3, las grasas buenas que nos protegen contra la inflamación y son importantes para la salud cardíaca y el colesterol.',
                'cantidad' => '14',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '10'
            ],
            [
                'nombre' => 'Coco',
                'imagen' => 'coco.png',
                'calorias' => '354',
                'carbohidratos' => '16',
                'proteinas' => '3',
                'grasas' => '33',
                'informacion' => 'Es un buen aliado para combatir la retencion de liquidos, ya que posee propiedades diureticas . Tambien tiene efecto laxante por su alto contenido en fibra.',
                'cantidad' => '30',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '4'
            ],
            [
                'nombre' => 'Mani',
                'imagen' => 'mani.png',
                'calorias' => '570',
                'carbohidratos' => '9',
                'proteinas' => '24',
                'grasas' => '49',
                'informacion' => 'Ayuda a reducir el colesterol malo y aumenta el colesterol bueno en el cuerpo debido a que contiene grasas mono-insaturadas, especialmente ácido oleico que ayuda a prevenir enfermedades coronarias.',
                'cantidad' => '14',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '4'
            ],
            [
                'nombre' => 'Nuez',
                'imagen' => 'nuez.png',
                'calorias' => '525',
                'carbohidratos' => '5',
                'proteinas' => '11',
                'grasas' => '52',
                'informacion' => 'Rebajan el nivel de colesterol malo LDL y la hipertensión.',
                'cantidad' => '4',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '4'
            ],
            [
                'nombre' => 'Palta',
                'imagen' => 'palta.png',
                'calorias' => '160',
                'carbohidratos' => '8',
                'proteinas' => '2',
                'grasas' => '15',
                'informacion' => 'Es muy rica en fibra por lo que ayuda a regular los niveles de azúcar en sangre y controlas la diabetes.',
                'cantidad' => '60',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '8'
            ],
            [
                'nombre' => 'Pistachos',
                'imagen' => 'pistacho.png',
                'calorias' => '560',
                'carbohidratos' => '27',
                'proteinas' => '21',
                'grasas' => '45',
                'informacion' => 'Los pistachos son ricos en fibra y proteínas, que aumentan la sensación de saciedad, ayudando a sentirte más lleno comiendo menos.',
                'cantidad' => '4',
                'medida' => 'grs',
                'clasificacion_id' => '3',
                'categoria_id' => '4'
            ],
            [
                'nombre' => 'Leche entera',
                'imagen' => 'leche.png',
                'calorias' => '60',
                'carbohidratos' => '5',
                'proteinas' => '3',
                'grasas' => '3',
                'informacion' => 'esarrollo oseo y defensa contra la osteoporosis.',
                'cantidad' => '100',
                'medida' => 'ml',
                'clasificacion_id' => '4',
                'categoria_id' => '5'
            ],
            [
                'nombre' => 'Queso',
                'imagen' => 'queso.png',
                'calorias' => '356',
                'carbohidratos' => '3',
                'proteinas' => '23',
                'grasas' => '28',
                'informacion' => 'Es un alimento rico en vitaminas A y D, ambas vitaminas ayudan al cuerpo a absorber el calcio y a mantener los huesos y los dientes sanos.',
                'cantidad' => '25',
                'medida' => 'grs',
                'clasificacion_id' => '4',
                'categoria_id' => '5'
            ],
            [
                'nombre' => 'Bebida soya',
                'imagen' => 'bebida_soya.png',
                'calorias' => '54',
                'carbohidratos' => '6',
                'proteinas' => '3.3',
                'grasas' => '1.8',
                'informacion' => 'Puede ayudar en la prevención de diferentes enfermedades cardiovasculares.',
                'cantidad' => '100',
                'medida' => 'ml',
                'clasificacion_id' => '4',
                'categoria_id' => '2'
            ],
            [
                'nombre' => 'Yogurt',
                'imagen' => 'yogurt.png',
                'calorias' => '59',
                'carbohidratos' => '3.6',
                'proteinas' => '10',
                'grasas' => '0.4',
                'informacion' => 'El yogur aporta un elevado contenido de nutrientes (fuente de proteínas, fuente de calcio) con muy pocas calorías.',
                'cantidad' => '100',
                'medida' => 'ml',
                'clasificacion_id' => '4',
                'categoria_id' => '5'
            ],
            [
                'nombre' => 'Acerola',
                'imagen' => 'acerola.png',
                'calorias' => '31',
                'carbohidratos' => '8',
                'proteinas' => '0',
                'grasas' => '0',
                'informacion' => 'La principal característica de la acerola es su altísimo contenido en vitamina C principalmente (aunque también tiene vitamina A).',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Platano',
                'imagen' => 'platano.png',
                'calorias' => '89',
                'carbohidratos' => '22.6',
                'proteinas' => '1',
                'grasas' => '0.34',
                'informacion' => 'Contiene un alto contenido en carbohidratos y en vitamina B por lo que al tomarlo cada dos horas entre  comidas controlamos el nivel de azúcar en sangre y la ansiedad por comer.',
                'cantidad' => '120',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Chirimoya',
                'imagen' => 'chirimoya.png',
                'calorias' => '75',
                'carbohidratos' => '18',
                'proteinas' => '2',
                'grasas' => '1',
                'informacion' => 'La gran cantidad de contenido en potasio, contribuye a mejorar tu salud cardíaca. Además, es un regulador natural de la presión arterial, y rica en antioxidantes que controlan los niveles de colesterol.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Durazno',
                'imagen' => 'durazno.png',
                'calorias' => '39',
                'carbohidratos' => '10',
                'proteinas' => '0.9',
                'grasas' => '0.3',
                'informacion' => 'Contiene vitamina A, la cual ayuda al mantenimiento de dientes, tejidos blandos y óseos.',
                'cantidad' => '150',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Frutilla',
                'imagen' => 'frutilla.png',
                'calorias' => '32',
                'carbohidratos' => '6',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Los beneficios de las fresas para la vista se encuentran en unos pigmentos que contienen (la zeaxantina y luteína) con efecto protector.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Granadilla',
                'imagen' => 'granada.png',
                'calorias' => '83',
                'carbohidratos' => '19',
                'proteinas' => '2',
                'grasas' => '1',
                'informacion' => 'Limpian los riñones, gracias a su alto contenido en potasio.',
                'cantidad' => '70',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Higo',
                'imagen' => 'higo.png',
                'calorias' => '74',
                'carbohidratos' => '19',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Las fibras solubles ayudan a controlar los niveles de colesterol y de glucosa en la sangre y contribuyen a regular el tránsito intestinal.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Kiwi',
                'imagen' => 'kiwi.png',
                'calorias' => '52',
                'carbohidratos' => '11',
                'proteinas' => '1',
                'grasas' => '1',
                'informacion' => 'Debido a la gran cantidad de vitamina C, el kiwi puede evitar el nerviosismo y la ansiedad, siendo perfecto también para reducir el estrés.',
                'cantidad' => '70',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Mandarina',
                'imagen' => 'mandarina.png',
                'calorias' => '34',
                'carbohidratos' => '8',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Por su alto contenido en vitamina C fortalece el sistema inmunitarios y reduce el riesgo de contraer enfermedades infecciosas y gripes.',
                'cantidad' => '90',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Mango',
                'imagen' => 'manga.png',
                'calorias' => '60',
                'carbohidratos' => '15',
                'proteinas' => '0.8',
                'grasas' => '0.4',
                'informacion' => 'Evita la retención de líquidos: Esta fruta tiene un gran efecto diurético, así que favorece la eliminación de líquidos.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Manzana',
                'imagen' => 'manzana.png',
                'calorias' => '46',
                'carbohidratos' => '12',
                'proteinas' => '0',
                'grasas' => '0',
                'informacion' => 'La manzana nos aporta vitaminas B1 y B6, que evitan el agotamiento mental y refuerzan la memoria.',
                'cantidad' => '180',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Naranja',
                'imagen' => 'naranja.png',
                'calorias' => '46',
                'carbohidratos' => '11',
                'proteinas' => '1',
                'grasas' => '0.2',
                'informacion' => 'Por su alto contenido en vitamina C aumenta las defensas y protege frente a los resfriados.',
                'cantidad' => '130',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Papaya',
                'imagen' => 'papaya.png',
                'calorias' => '45',
                'carbohidratos' => '10.3',
                'proteinas' => '0.6',
                'grasas' => '0.2',
                'informacion' => 'Evita la retención de líquidos así que ayuda en dietas de adelgazamiento y reduce la hinchazón abdominal.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Pera',
                'imagen' => 'pera.png',
                'calorias' => '41',
                'carbohidratos' => '11',
                'proteinas' => '0',
                'grasas' => '0',
                'informacion' => 'Su consumo favorece una buena digestion, desinflama la mucuosa intestinal y tiene un suave efecto diuretico y laxante.',
                'cantidad' => '180',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Piña',
                'imagen' => 'piña.png',
                'calorias' => '46',
                'carbohidratos' => '12',
                'proteinas' => '0',
                'grasas' => '0',
                'informacion' => 'Es saciante: la piña, al contener mucha agua, nos hace sentir satisfechos y puede evitar que comamos en exceso.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Pomelo',
                'imagen' => 'pomelo.png',
                'calorias' => '42',
                'carbohidratos' => '10',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Contienen Vitamina C: imprescindible para la formación del colágeno en los huesos, músculos, cartílagos y vasos sanguíneos',
                'cantidad' => '250',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Sandia',
                'imagen' => 'sandia.png',
                'calorias' => '37',
                'carbohidratos' => '8',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'La sandía posee propiedades depurativas y provoca una sensación de saciedad que puede ser útil en las dietas de adelgazamiento.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],
            [
                'nombre' => 'Uva',
                'imagen' => 'uva.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'cantidad' => '100',
                'medida' => 'grs',
                'clasificacion_id' => '5',
                'categoria_id' => '3'
            ],

            /*desde aca las ensaladas*/
            /*
            [
                'nombre' => 'Acelga',
                'imagen' => 'acelga.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Apio',
                'imagen' => 'apio.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Uva',
                'imagen' => 'uva.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Brocoli',
                'imagen' => 'brocoli.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Cebolla',
                'imagen' => 'cebolla.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Coliflor',
                'imagen' => 'coliflor.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Espinaca',
                'imagen' => 'espinaca.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Lechuga',
                'imagen' => 'lechuga.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Pepino',
                'imagen' => 'pepino.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Pimenton',
                'imagen' => 'pimenton.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Rabano',
                'imagen' => 'rabano.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Remolacha',
                'imagen' => 'remolacha.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Tomate',
                'imagen' => 'tomate.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Zanahoria',
                'imagen' => 'zanahoria.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            [
                'nombre' => 'Zapallo',
                'imagen' => 'zapallo.png',
                'calorias' => '61',
                'carbohidratos' => '16',
                'proteinas' => '1',
                'grasas' => '0',
                'informacion' => 'Favorecen el buen estado de las arterias y del corazon, mejoran la vasodilatacion y disminuyen el riesgo de trombosis.',
                'clasificacion_id' => '6',
                'categoria_id' => '7'
            ],
            */
        );

        Alimento::insert($data);
    }
}
